services:
  clipboard-landing-page:
    build: ./
    stdin_open: true
    tty: true
    container_name: clipboard-landing-page-app
    ports:
      - '10009:4173'
      - '11009:5173'
    volumes:
      - ./:/app
      - clipboard-landing-page-nm:/app/node_modules
volumes:
  clipboard-landing-page-nm:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./node_modules
